### ISSUE TITLE
It's broken

### ISSUE THREAD

**Issue by SpheMakh** [wits-cfa/simms#47]

**Comment by SpheMakh** [comment]
@MukundiRams @Allycan also see how they create the MS in this script 

https://github.com/ska-sa/katdal/blob/master/scripts%2Fmvftoms.py

**Comment by MukundiRams** [comment]
@SpheMakh will do.

**Comment by MukundiRams** [comment]
@SpheMakh I added some missing columns on the measurement set. To test it, I wrote a small Stimela script to image the measurement set using wsclean and it gave me an image. I also tried adding some noise in the measurement set and imaged it, I got the image with noise as expected. I pushed these changes on the issue-47 branch.

**Comment by Allycan** [comment]
@MukundiRams 👍  thank you for your swift action on this. I was intending to attend to up after my IAU poster preparation.

**Comment by MukundiRams** [comment]
@Allycan no problem. If you get a chance, please test and see if it works accordingly.

**Comment by SpheMakh** [comment]
Fixed
