### ISSUE TITLE
It's slow

### ISSUE THREAD

**Issue by Allycan** [wits-cfa/simms#50]
Creating the measurement set as well as computing visibilities is slow, especially for larger arrays. For instance,  for the simulation of an SKA array observation with `0.5h` observation time with a dump-rate of `8s`: `--telsim` takes about 7 minutes (six and a half minutes of this time is taken by updating the pointing sub-table) while `--skysim` takes 49 hours to compute visibilities.

**Comment by SpheMakh** [comment]
Woah! That's way too much time, especially for the simulation.  We need to use exclusively for both telsim and skysim.

**Comment by SpheMakh** [comment]
Fixed
